version: '3.7'

services:
  server:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        GIT_USER_NAME: mounir-bennacer
        GIT_USER_EMAIL: benphaoris@gmail.com
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
